### ISSUE TITLE
Exposed fields update

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/literature-ws#1]
I've gone through all the fields and my suggestions are as follows:

- [x]  remove the following fields from responses as they provide no usable information:

authored
confirmed
contentType
country
fileAttached
groupId
hidden
privatePublication
profileId
read
searchable
starred
userContext

- [x] investigate source of this field, because it's unclear to me

gbifRegion

- [x] rename the following fields in responses

accessed -> discovered
created -> added
createdAt -> published
updatedAt -> modified

**Comment by mike-podolskiy90** [comment]
@dnoesgaard What's wrong with the gbifRegion field?

**Comment by dnoesgaard** [comment]
I just don't know what it means or what it's based on. It must be derived by the content-crawler somehow...

**Comment by mike-podolskiy90** [comment]
I hope @fmendezh or @MortenHofft can help us

**Comment by fmendezh** [comment]
The gbifRegion field is derived thru the link we have to the "Vocabulary: Countries" content model

**Comment by dnoesgaard** [comment]
But data from Mendeley is it based on?

**Comment by fmendezh** [comment]
> But what data from Mendeley is it based on?

Sorry, I  reviewed the contentful crawler, not the Mendeley one :) 
The region is interpreted from the Mendeley tags, it seems that we tag elements with something like "country_biodiversity" or something similar, and we derived the region from that country

**Comment by dnoesgaard** [comment]
Ok. I don't think this was ever used for anything, but it does seem consistent, e.g. http://api.gbif.org/v1/literature/search?q=cc612d90-460e-3dc9-9cb6-0418de9839dc has two different regions.

We can leave it, if you think it makes sense.
