### ISSUE TITLE
get single literature entry

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/literature-ws#2]
Is is possible to have this behavior for retrieving a specific paper:

GET /literature/cc612d90-460e-3dc9-9cb6-0418de9839dc

-or-

GET /literature/search?id=cc612d90-460e-3dc9-9cb6-0418de9839dc

Thanks!

**Comment by mike-podolskiy90** [comment]
Yes, we can do that

**Comment by mike-podolskiy90** [comment]
GET /literature/cc612d90-460e-3dc9-9cb6-0418de9839dc
deployed to prod
