### ISSUE TITLE
DOI as a separately searchable field

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/literature-ws#3]
Please allow specific DOI searching e.g. /search?doi=10.1038/s41598-019-45491-7

**Comment by mike-podolskiy90** [comment]
Is it possible that one DOI corresponds to several literature items as identifier?
If not I suggest mapping to be GET /literature/{DOI}

**Comment by dnoesgaard** [comment]
Good question. One DOI should only correspond to one identifier. So perhaps you're right.

**Comment by mike-podolskiy90** [comment]
I deployed that to dev

**Comment by dnoesgaard** [comment]
There are some that don't work e.g.

10.1134/S1995425520050030
10.1093/sysbio/syaa080
10.17223/19988591/50/2
10.22541/au.160373183.39716449/v1
10.1111/2041-210X.13523

**Comment by mike-podolskiy90** [comment]
Thank you for testing, I'll check those

**Comment by mike-podolskiy90** [comment]
It seems that because of additional slashes and capital letters. Gonna commit an update to fix that

**Comment by MattBlissett** [comment]
I think you already know, but remember DOIs are case-**in**sensitive.

**Comment by mike-podolskiy90** [comment]
redeployed

**Comment by dnoesgaard** [comment]
Looking good. Doing some extensive testing now and will let you know the results shortly.

**Comment by dnoesgaard** [comment]
These are causing problems:

10.1603/0022-2585(2008)45[775:awrdfm]2.0.co;2
10.1579/0044-7447(2008)37[138:lbrapi]2.0.co;2
10.1603/0046-225x(2008)37[442:saoxgc]2.0.co;2
10.1639/0007-2745(2008)111[140:rlob]2.0.co;2
10.1898/1051-1733(2006)87[80:BICAOF]2.0.CO;2

(DOIs are horrible, I know, sorry...)

**Comment by mike-podolskiy90** [comment]
Wow, those are indeed terrible. Never seen such DOIs. Thank you for discovering them, I'll fix those

**Comment by dnoesgaard** [comment]
Good news is that the remaining 9900+ DOIs I tested worked fine :)

**Comment by mike-podolskiy90** [comment]
Since we have so many problems with this I decided to do more testing.
I discovered that we have several DOIs which are related to several literature items: 

- 10.16108/j.issn1006-7493.2020022.

I also found some literature with invalid DOI: 

- 88d01c90-3dfc-3239-b628-c3d22193a2ff

So I'm going to change this to GET /search?doi={doi}

**Comment by mike-podolskiy90** [comment]
@dnoesgaard seems fine now
/literature/serach?doi={doi}

**Comment by dnoesgaard** [comment]
Thanks, Mikhail. This is very useful. I will make sure these are fixed.

**Comment by dnoesgaard** [comment]
(I edited your comment to keep track of the items)

**Comment by dnoesgaard** [comment]
Ug, that last one has 18 records. Yikes, that's bad...

**Comment by mike-podolskiy90** [comment]
Can we close this?

**Comment by dnoesgaard** [comment]
Sure. I'll deal with the last one separately.
