### ISSUE TITLE
Literature citation download file is exactly 50k rows (excluding header)

### ISSUE THREAD

**Issue by ymgan** [gbif/literature-ws#32]
Hi,

The literature citation file (https://api.gbif.org/v1/literature/export?format=TSV&) is exactly 50,000 records. May I know if this is normal please?

Thank you so much!

**Comment by ahakanzn** [comment]
I have changed the maxResultWindow to 60000 and it will be fine until we have more than 60000 records. I'll work on a permanent solution in the meantime.
