### ISSUE TITLE
Exact matching for searching for websites

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/literature-ws#37]
The ability to identify duplicate entries is crucial, but searching for URLs (websites) uses fuzzy matching, so that searching for e.g. https://doi.org/10.1002/ppp3.10518, gives all these entries:

> https://doi.org/10.1002/ppp3.10156
https://doi.org/10.1002/ppp3.10308
https://doi.org/10.1002/ppp3.10110
https://doi.org/10.1002/ppp3.10410
https://doi.org/10.1002/ppp3.10251
https://doi.org/10.1002/ppp3.10148
https://doi.org/10.1002/ppp3.10113
https://doi.org/10.1002/ppp3.10438
https://doi.org/10.1002/ppp3.10506
https://doi.org/10.1002/ppp3.10522
https://doi.org/10.1002/ppp3.10532

Can we find a solution to avoid this? Either by adding a new specific param for websites with 100% matching or a (non-default) new param to allow 100% matching only?

**Comment by ahakanzn** [comment]
New parameter "websites" created and deployed to prod.
-> https://api.gbif.org/v1/literature/search?websites=https://doi.org/10.1002/ppp3.10308
-> https://api.gbif.org/v1/literature/search?websites=https://doi.org/10.1002/ppp3.10308&websites=https://doi.org/10.1002/ppp3.10113
