### ISSUE TITLE
decorate literature with publisher countries

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/literature-ws#40]
When building the literature index, is it feasible to extract countries for all `publishingOrganizationKey`s to allow searches for publications using data from a given country?

**Comment by dnoesgaard** [comment]
To be clear, it's the countries of the publishers I'm looking for. We've already got the publishers (in `publishingOrganizationKey`)

**Comment by MattBlissett** [comment]
I think Fede meant to write `publishingCountry`, similar to https://api.gbif.org/v1/occurrence/search?publishingCountry=FO

**Comment by ahakanzn** [comment]
deployed to prod
