### ISSUE TITLE
SQL download error

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/literature-ws#45]
https://builds.gbif.org/job/run-content-crawler/24769/consoleText

> feign.FeignException: Cannot parse SQL_TSV_ZIP into a known DownloadFormat (through reference chain: org.gbif.api.model.occurrence.Download["request"]) reading GET http://api.gbif.org/v1/occurrence/download/0083528-240321170329656

(note, I manually removed `eraseAfter` for the download in question)

**Comment by ahakanzn** [comment]
This was caused by an outdated library, which has now been upgraded, so everything should be fine now.
