### ISSUE TITLE
better feedback for invalid queries

### ISSUE THREAD

**Issue by MortenHofft** [gbif/literature-ws#5]
This is prompted by me forgetting an `*` and being confused by the lack of an informative error message.

https://api.gbif.org/v1/occurrence/search?limit=20&offset=0&year=2000,
returns `Invalid integer range: 2000,`

https://api.gbif.org/v1/literature/search?limit=20&offset=0&year=2000,
returns
```
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Fri Aug 13 14:17:14 UTC 2021
There was an unexpected error (type=Internal Server Error, status=500).
```

**Comment by mike-podolskiy90** [comment]
literature v1.11, closing this
