### ISSUE TITLE
Derived datasets response incorrect

### ISSUE THREAD

**Issue by timrobertson100** [gbif/literature-ws#7]
The results on [this webpage](https://www.gbif.org/resource/search?contentType=literature&publishingOrganizationKey=eb07eeb0-3db9-11d9-8439-b8a03c50a862) appear as:

<img width="801" alt="image" src="https://user-images.githubusercontent.com/237221/155673741-6d984f46-2b57-4f3a-a5f7-546da9e303dc.png">

The [API response](https://api.gbif.org/v1/literature/search?publishingOrganizationKey=eb07eeb0-3db9-11d9-8439-b8a03c50a862) is returning:

```
{
  "title": "Derived dataset",
  "abstract": "(no abstract available)",
  ...
}
```

However, if you click through to a record ([example](https://www.gbif.org/derivedDataset/10.15468/dd.zmvh5v)) it does have a title and a description.

I don't think the API search response is populating those correctly.

**Comment by mike-podolskiy90** [comment]
Thanks Tim, I'll check it

**Comment by timrobertson100** [comment]
Thanks @mike-podolskiy90

**Comment by dnoesgaard** [comment]
This is populated by Mendeley and is exactly as I entered. No bugs here.
