### ISSUE TITLE
Enable search by project and programme

### ISSUE THREAD

**Issue by timrobertson100** [gbif/literature-ws#8]
Expose the ability to search for literature based on the projects or programmes connected to the datasets (either direct citation of the dataset, or downloads that include them).

The intention is to be able to showcase the scientific papers that have been published that made use of datasets connected with e.g. the BID programme.

This will require changes in the backend that builds the index as well.

**Comment by fmendezh** [comment]
now in prod with project identifiers, network and gbifProgramme filters and facets

[https://api.gbif.org/v1/literature/search?facet=gbifProgramme&facet=gbifProjectIdentifier](https://api.gbif.org/v1/literature/search?facet=gbifProgramme&facet=gbifProjectIdentifier)

[https://api.gbif.org/v1/literature/search?gbifProgramme=BID](https://api.gbif.org/v1/literature/search?gbifProgramme=BID)

[https://api.gbif.org/v1/literature/search?gbifProjectIdentifier=BIFA4_015](https://api.gbif.org/v1/literature/search?gbifProjectIdentifier=BIFA4_015)

[https://api.gbif.org/v1/literature/search?gbifNetworkKey=379a0de5-f377-4661-9a30-33dd844e7b9a](https://api.gbif.org/v1/literature/search?gbifNetworkKey=379a0de5-f377-4661-9a30-33dd844e7b9a)

[https://api.gbif.org/v1/literature/search?facet=gbifNetworkKey](https://api.gbif.org/v1/literature/search?facet=gbifNetworkKey)
