### ISSUE TITLE
Enable search by network

### ISSUE THREAD

**Issue by MortenHofft** [gbif/literature-ws#9]
Expose the ability to search for literature based on the networks (plural) a dataset might belong to.

The intention is to be able to showcase the scientific papers that have been published that made use of datasets connected with e.g. hosted portals that scope their data by a network. It will also make it possible to show citation metrics for e.g. the OBIS network

This will require changes in the backend that builds the index as well.

**Comment by fmendezh** [comment]
now in prod with project identifiers, network and gbifProgramme filters and facets

[https://api.gbif.org/v1/literature/search?facet=gbifProgramme&facet=gbifProjectIdentifier](https://api.gbif.org/v1/literature/search?facet=gbifProgramme&facet=gbifProjectIdentifier)

[https://api.gbif.org/v1/literature/search?gbifProgramme=BID](https://api.gbif.org/v1/literature/search?gbifProgramme=BID)

[https://api.gbif.org/v1/literature/search?gbifProjectIdentifier=BIFA4_015](https://api.gbif.org/v1/literature/search?gbifProjectIdentifier=BIFA4_015)

[https://api.gbif.org/v1/literature/search?gbifNetworkKey=379a0de5-f377-4661-9a30-33dd844e7b9a](https://api.gbif.org/v1/literature/search?gbifNetworkKey=379a0de5-f377-4661-9a30-33dd844e7b9a)

[https://api.gbif.org/v1/literature/search?facet=gbifNetworkKey](https://api.gbif.org/v1/literature/search?facet=gbifNetworkKey)
